eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:9527/eureka/
  server:
    enable-self-preservation: false

server:
  port: 9527
spring:
  application:
    name: eureka-server